services:
    intercom_app.handler:
        class: TomPedals\HelpScoutApp\Intercom\IntercomAppHandler
        arguments:
            - '@twig'
            - '@intercom_app.client'
            - null
            - null

    intercom_app.action:
        class: TomPedals\HelpScoutApp\AppAction
        arguments:
            - '@help_scout_app.request_factory'
            - '@intercom_app.handler'

    intercom_app.client:
        class: Intercom\IntercomClient
        public: false
        arguments:
            - null
            - null
